In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

### Problem Statement:

- The Indian bike market offers numerous options with different prices, mileage, engine capacities, and ratings, making it difficult for customers to choose the best bike. This project aims to collect bike data from BikeWale through web scraping and analyze key features. The goal is to identify and rank the best-performing bikes using data-driven insights.

In [2]:
url = "https://www.bikewale.com/new-bike-search/?page=1"
url

'https://www.bikewale.com/new-bike-search/?page=1'

In [3]:

bike_name = []
rating = []
total_ratings = []
engine_cc = []
mileage = []
power = []
weight = []
price = []

headers = {
    "User-Agent": "Mozilla/5.0"
}

for i in range(1,15):

    url = f"https://www.bikewale.com/new-bike-search/?page={i}"

    response = requests.get(url, headers=headers)

    soup = BeautifulSoup(response.text, "html.parser")

    cards = soup.find_all("h3", class_="o-c6")

    print(f"Page {i}: {len(cards)}")

    for card in cards:

        text = card.parent.parent.parent.get_text(" | ", strip=True)

        parts = [x.strip() for x in text.split("|") if x.strip()]

        bike_name.append(parts[0])

        rating.append(parts[1] if len(parts) > 1 else None)

        total_ratings.append(
            next((x for x in parts if "Ratings" in x), None)
        )

        engine_cc.append(
            next((x for x in parts if "cc" in x), None)
        )

        mileage.append(
            next((x for x in parts if "kmpl" in x), None)
        )

        power.append(
            next((x for x in parts if "bhp" in x), None)
        )

        weight.append(
            next((x for x in parts if "kg" in x), None)
        )

        price.append(
            next((x for x in parts if "₹" in x), None)
        )

Page 1: 30
Page 2: 30
Page 3: 30
Page 4: 30
Page 5: 30
Page 6: 30
Page 7: 30
Page 8: 30
Page 9: 30
Page 10: 30
Page 11: 30
Page 12: 30
Page 13: 30
Page 14: 30

In [4]:
print(response)
print(response.status_code)
print(response.url)
print(response.text[:500])

<Response [200]>
200
https://www.bikewale.com/new-bike-search/?page=14
<!DOCTYPE html><html lang="en" itemscope itemtype="http://schema.org/WebPage" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#"><head><link rel="preload" href="https://stc.aeplcdn.com/fonts/lato-bold.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="https://stc.aeplcdn.com/fonts/lato-regular.woff2" as="font" type="font/woff2" crossorigin><link rel="manifest" href="/manifest.webmanifest.json">
    <title data-react-helmet="true" itemprop="name">Search New Bikes by Bra

In [5]:
print(len(bike_name))
print(len(rating))
print(len(total_ratings))
print(len(engine_cc))
print(len(mileage))
print(len(power))
print(len(weight))
print(len(price))

420
420
420
420
420
420
420
420

In [6]:
df = pd.DataFrame({
    "Bike_Name": bike_name,
    "Rating": rating,
    "Total_Ratings": total_ratings,
    "Engine_CC": engine_cc,
    "Mileage": mileage,
    "Power_BHP": power,
    "Weight_KG": weight,
    "Price": price
})

print(df.shape)
df.head()

(420, 8)

,Bike_Name,Rating,Total_Ratings,Engine_CC,Mileage,Power_BHP,Weight_KG,Price
0,EV,Bajaj Chetak,655 Ratings,None,None,None,None,"₹ 1,10,922"
1,Bajaj Pulsar N160,4.6,1221 Ratings,164.82 cc,51.6 kmpl,15.68 bhp,152 kg,"₹ 1,16,506"
2,EV,TVS iQube,773 Ratings,None,None,None,129.7 kg,"₹ 1,13,742"
3,Royal Enfield Hunter 350,4.7,1569 Ratings,349.34 cc,36.2 kmpl,20.2 bhp,181 kg,"₹ 1,37,648"
4,Royal Enfield Classic 350,4.7,1306 Ratings,349 cc,35 kmpl,20.2 bhp,195 kg,"₹ 1,85,859"

In [7]:
print("Bike Names:", len(bike_name))
print("Ratings:", len(rating))
print("Total Ratings:", len(total_ratings))
print("Engine CC:", len(engine_cc))
print("Mileage:", len(mileage))
print("Power:", len(power))
print("Weight:", len(weight))
print("Prices:", len(price))

Bike Names: 420
Ratings: 420
Total Ratings: 420
Engine CC: 420
Mileage: 420
Power: 420
Weight: 420
Prices: 420

In [8]:
df.head(5)

,Bike_Name,Rating,Total_Ratings,Engine_CC,Mileage,Power_BHP,Weight_KG,Price
0,EV,Bajaj Chetak,655 Ratings,None,None,None,None,"₹ 1,10,922"
1,Bajaj Pulsar N160,4.6,1221 Ratings,164.82 cc,51.6 kmpl,15.68 bhp,152 kg,"₹ 1,16,506"
2,EV,TVS iQube,773 Ratings,None,None,None,129.7 kg,"₹ 1,13,742"
3,Royal Enfield Hunter 350,4.7,1569 Ratings,349.34 cc,36.2 kmpl,20.2 bhp,181 kg,"₹ 1,37,648"
4,Royal Enfield Classic 350,4.7,1306 Ratings,349 cc,35 kmpl,20.2 bhp,195 kg,"₹ 1,85,859"

In [9]:

df.tail()

,Bike_Name,Rating,Total_Ratings,Engine_CC,Mileage,Power_BHP,Weight_KG,Price
415,Yamaha XSR 155,4.6,222 Ratings,155 cc,46 kmpl,18.1 bhp,137 kg,"₹ 1,50,957"
416,Bajaj Pulsar N250,4.6,405 Ratings,249 cc,44 kmpl,24.1 bhp,162 kg,"₹ 1,38,828"
417,Bajaj Pulsar NS125,4.5,953 Ratings,124.45 cc,46.9 kmpl,11.8 bhp,144 kg,"₹ 94,048"
418,Harley-Davidson X440,4.8,783 Ratings,440 cc,35 kmpl,27 bhp,190.5 kg,"₹ 2,35,016"
419,Triumph Speed 400,3.7,30 Ratings,349 cc,28 kmpl,36.49 bhp,179 kg,"₹ 2,34,296"

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bike_Name      420 non-null    object
 1   Rating         420 non-null    object
 2   Total_Ratings  420 non-null    object
 3   Engine_CC      392 non-null    object
 4   Mileage        392 non-null    object
 5   Power_BHP      392 non-null    object
 6   Weight_KG      406 non-null    object
 7   Price          420 non-null    object
dtypes: object(8)
memory usage: 26.4+ KB

In [11]:
print(len(df))

420